const { test } = require('node:test'); const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs');
require('reflect-metadata'); process.loadEnvFile('.env');
const { PrismaClient } = require('@prisma/client'); const { NestFactory } = require('@nestjs/core'); const { PasswordService } = require('../dist/common/security/password.service'); const { configureApplication } = require('../dist/config/configure-app');
const { AiUmlProposalService } = require('../dist/ai/ai-uml-proposal.service');

test('Fase 4A genera y valida propuestas UML sin persistirlas', async t => {
 const schema = `arqnova_test_${randomUUID().replaceAll('-', '')}`; const root = new PrismaClient(); let temp; let app; const originalUrl = process.env.DATABASE_URL; const originalProvider = process.env.AI_PROVIDER;
 try {
  await root.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`); const url = new URL(originalUrl); url.searchParams.set('schema', schema); process.env.DATABASE_URL = url.toString(); process.env.AI_PROVIDER = 'mock'; temp = new PrismaClient({ datasources: { db: { url: url.toString() } } });
  for (const directory of fs.readdirSync('prisma/migrations').sort()) { const migration = `prisma/migrations/${directory}/migration.sql`; if (fs.existsSync(migration)) for (const sql of fs.readFileSync(migration, 'utf8').split(';').map(value => value.trim()).filter(Boolean)) await temp.$executeRawUnsafe(sql); }
  const roles = {}; for (const name of ['ADMINISTRADOR', 'ANFITRION', 'COLABORADOR']) roles[name] = await temp.role.create({ data: { name } }); const passwords = new PasswordService();
  const createUser = async role => { const password = randomBytes(24).toString('hex'); const user = await temp.user.create({ data: { name: role, email: `${randomUUID()}@example.test`, passwordHash: await passwords.hash(password), roleId: roles[role].id } }); return { ...user, password }; };
  const host = await createUser('ANFITRION'); const member = await createUser('COLABORADOR'); const outsider = await createUser('COLABORADOR'); const admin = await createUser('ADMINISTRADOR'); const project = await temp.project.create({ data: { name: 'IA 4A', ownerId: host.id, members: { create: { userId: member.id } } } });
  const { AppModule } = require('../dist/app.module'); app = await NestFactory.create(AppModule, { logger: false }); configureApplication(app); await app.listen(0, '127.0.0.1'); const base = `${await app.getUrl()}/api`;
  const call = async (path, method = 'GET', body, token) => { const headers = { Accept: 'application/json', 'Content-Type': 'application/json' }; if (token) headers.Authorization = `Bearer ${token}`; const response = await fetch(`${base}${path}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) }); const data = await response.json(); assert.equal(JSON.stringify(data).includes('passwordHash'), false); return { status: response.status, data }; };
  const tokenFor = async user => (await call('/auth/login', 'POST', { email: user.email, password: user.password })).data.accessToken; const hostToken = await tokenFor(host); const memberToken = await tokenFor(member); const outsiderToken = await tokenFor(outsider); const adminToken = await tokenFor(admin); const path = `/projects/${project.id}/ai/uml-proposal`;

  await t.test('anfitrión y colaborador obtienen propuesta determinista del mock', async () => { for (const token of [hostToken, memberToken]) { const result = await call(path, 'POST', { prompt: 'Crea Cliente y Pedido' }, token); assert.equal(result.status, 201); assert.deepEqual(result.data.proposal.classes.map(item => item.name), ['Cliente', 'Pedido']); assert.equal(result.data.proposal.relations[0].targetMultiplicity, '0..*'); } });
  await t.test('sin JWT, externo y administrador sin membresía son bloqueados', async () => { assert.equal((await call(path, 'POST', { prompt: 'modelo' })).status, 401); assert.equal((await call(path, 'POST', { prompt: 'modelo' }, outsiderToken)).status, 403); assert.equal((await call(path, 'POST', { prompt: 'modelo' }, adminToken)).status, 403); });
  await t.test('prompt vacío, propiedad ajena y longitud excesiva son rechazados', async () => { assert.equal((await call(path, 'POST', { prompt: '' }, hostToken)).status, 400); assert.equal((await call(path, 'POST', { prompt: 'modelo', secret: 'no' }, hostToken)).status, 400); assert.equal((await call(path, 'POST', { prompt: 'a'.repeat(2001) }, hostToken)).status, 400); });
  await t.test('la propuesta no crea ni modifica el diagrama', async () => { assert.equal(await temp.diagram.count({ where: { projectId: project.id } }), 0); await call(path, 'POST', { prompt: 'modelo' }, hostToken); assert.equal(await temp.diagram.count({ where: { projectId: project.id } }), 0); assert.equal(await temp.umlClass.count(), 0); assert.equal(await temp.umlRelation.count(), 0); });

  const service = provider => new AiUmlProposalService(provider, { get: (_key, fallback) => fallback === 10_000 ? 20 : fallback });
  const valid = { classes: [{ name: 'Cliente', attributes: [], methods: [] }], relations: [] };
  await t.test('JSON inválido y respuesta vacía se rechazan', async () => { await assert.rejects(() => service({ generateUmlProposal: async () => '{' }).generate('x'), error => error.getStatus() === 502); await assert.rejects(() => service({ generateUmlProposal: async () => '' }).generate('x'), error => error.getStatus() === 502); });
  await t.test('clases y atributos duplicados se rechazan', async () => { await assert.rejects(() => service({ generateUmlProposal: async () => ({ classes: [{ name: 'Cliente', attributes: [], methods: [] }, { name: 'cliente', attributes: [], methods: [] }], relations: [] }) }).generate('x'), /clases duplicadas/); await assert.rejects(() => service({ generateUmlProposal: async () => ({ classes: [{ name: 'Cliente', attributes: [{ name: 'id', type: 'Long', visibility: 'PRIVATE' }, { name: 'ID', type: 'UUID', visibility: 'PRIVATE' }], methods: [] }], relations: [] }) }).generate('x'), /atributos duplicados/); });
  await t.test('relación inexistente y multiplicidad inválida se rechazan', async () => { await assert.rejects(() => service({ generateUmlProposal: async () => ({ ...valid, relations: [{ sourceClassName: 'Cliente', targetClassName: 'Pedido', type: 'ASSOCIATION' }] }) }).generate('x'), /clases inexistentes/); await assert.rejects(() => service({ generateUmlProposal: async () => ({ ...valid, relations: [{ sourceClassName: 'Cliente', targetClassName: 'Cliente', type: 'ASSOCIATION', sourceMultiplicity: 'muchos' }] }) }).generate('x'), error => error.getStatus() === 502); });
  await t.test('campos inesperados y visibilidad inválida se rechazan', async () => { await assert.rejects(() => service({ generateUmlProposal: async () => ({ ...valid, extra: true }) }).generate('x'), error => error.getStatus() === 502); await assert.rejects(() => service({ generateUmlProposal: async () => ({ classes: [{ name: 'Cliente', attributes: [{ name: 'id', type: 'Long', visibility: 'SECRET' }], methods: [] }], relations: [] }) }).generate('x'), error => error.getStatus() === 502); });
  await t.test('proveedor no disponible y timeout se traducen a errores controlados', async () => { await assert.rejects(() => service({ generateUmlProposal: async () => { throw new Error('clave privada'); } }).generate('x'), error => error.getStatus() === 503 && !error.message.includes('clave privada')); await assert.rejects(() => service({ generateUmlProposal: () => new Promise(resolve => setTimeout(() => resolve(valid), 100)) }).generate('x'), error => error.getStatus() === 504); });
 } finally { if (app) await app.close(); if (temp) await temp.$disconnect(); process.env.DATABASE_URL = originalUrl; if (originalProvider === undefined) delete process.env.AI_PROVIDER; else process.env.AI_PROVIDER = originalProvider; await root.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await root.$disconnect(); }
});
