const { test } = require('node:test'); const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs');
require('reflect-metadata'); process.loadEnvFile('.env');
const { PrismaClient } = require('@prisma/client'); const { NestFactory } = require('@nestjs/core'); const { io } = require('../../frontend/node_modules/socket.io-client'); const { PasswordService } = require('../dist/common/security/password.service'); const { configureApplication } = require('../dist/config/configure-app');

test('CU07 aplica propuestas UML aditivas, atómicas y realtime', async t => {
 const schema = `arqnova_test_${randomUUID().replaceAll('-', '')}`; const root = new PrismaClient(); let temp; let app; let socket; const originalUrl = process.env.DATABASE_URL; const originalProvider = process.env.AI_PROVIDER;
 try {
  await root.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`); const url = new URL(originalUrl); url.searchParams.set('schema', schema); process.env.DATABASE_URL = url.toString(); process.env.AI_PROVIDER = 'mock'; temp = new PrismaClient({ datasources: { db: { url: url.toString() } } });
  for (const directory of fs.readdirSync('prisma/migrations').sort()) { const migration = `prisma/migrations/${directory}/migration.sql`; if (fs.existsSync(migration)) for (const sql of fs.readFileSync(migration, 'utf8').split(';').map(value => value.trim()).filter(Boolean)) await temp.$executeRawUnsafe(sql); }
  const roles = {}; for (const name of ['ADMINISTRADOR', 'ANFITRION', 'COLABORADOR']) roles[name] = await temp.role.create({ data: { name } }); const passwords = new PasswordService();
  const createUser = async role => { const password = randomBytes(24).toString('hex'); const user = await temp.user.create({ data: { name: role, email: `${randomUUID()}@example.test`, passwordHash: await passwords.hash(password), roleId: roles[role].id } }); return { ...user, password }; };
  const host = await createUser('ANFITRION'); const member = await createUser('COLABORADOR'); const outsider = await createUser('COLABORADOR'); const admin = await createUser('ADMINISTRADOR'); const project = await temp.project.create({ data: { name: 'CU07', ownerId: host.id, members: { create: { userId: member.id } } } });
  const { AppModule } = require('../dist/app.module'); app = await NestFactory.create(AppModule, { logger: false }); configureApplication(app); await app.listen(0, '127.0.0.1'); const origin = await app.getUrl(); const base = `${origin}/api`;
  const call = async (path, method = 'GET', body, token) => { const response = await fetch(`${base}${path}`, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) }); const data = await response.json(); assert.equal(JSON.stringify(data).includes('passwordHash'), false); return { status: response.status, data }; };
  const tokenFor = async user => (await call('/auth/login', 'POST', { email: user.email, password: user.password })).data.accessToken; const hostToken = await tokenFor(host); const memberToken = await tokenFor(member); const outsiderToken = await tokenFor(outsider); const adminToken = await tokenFor(admin); const applyPath = `/projects/${project.id}/ai/apply-uml-proposal`;
  const proposal = { classes: [{ name: 'Cliente', attributes: [{ name: 'id', type: 'Long', visibility: 'PRIVATE', isPrimaryKey: true }], methods: [{ name: 'registrar', returnType: 'void', visibility: 'PUBLIC' }] }, { name: 'Pedido', attributes: [{ name: 'total', type: 'Decimal', visibility: 'PRIVATE' }], methods: [] }], relations: [{ sourceClassName: 'Cliente', targetClassName: 'Pedido', type: 'ASSOCIATION', sourceMultiplicity: '1', targetMultiplicity: '0..*', label: 'realiza' }] };

  await t.test('propuesta se genera y requiere autenticación/acceso al aplicarse', async () => { assert.equal((await call(`/projects/${project.id}/ai/uml-proposal`, 'POST', { prompt: 'Crea Cliente y Pedido' }, hostToken)).status, 201); assert.equal((await call(applyPath, 'POST', { proposal })).status, 401); assert.equal((await call(applyPath, 'POST', { proposal }, outsiderToken)).status, 403); assert.equal((await call(applyPath, 'POST', { proposal }, adminToken)).status, 403); });
  await t.test('persistencia completa, posiciones distribuidas y broadcast posterior al commit', async () => { socket = io(`${origin}/collaboration`, { auth: { token: memberToken }, transports: ['websocket'], forceNew: true }); await new Promise((resolve, reject) => { socket.once('connect', resolve); socket.once('connect_error', reject) }); const joined = await socket.timeout(3000).emitWithAck('project:join', { projectId: project.id }); assert.equal(joined.ok, true); const eventPromise = new Promise(resolve => socket.once('uml:diagram:updated', resolve)); const result = await call(applyPath, 'POST', { proposal }, hostToken); assert.equal(result.status, 201); assert.deepEqual(result.data.created, { classes: 2, attributes: 2, methods: 1, relations: 1 }); assert.equal(result.data.diagram.classes.length, 2); assert.notDeepEqual(result.data.diagram.classes.map(item => [item.x, item.y]), [[0, 0], [0, 0]]); const event = await eventPromise; assert.equal(event.diagram.classes.length, 2); assert.equal(await temp.umlClass.count({ where: { diagram: { projectId: project.id } } }), 2); assert.equal(await temp.umlRelation.count({ where: { diagram: { projectId: project.id } } }), 1); });
  await t.test('colaborador puede aplicar de forma aditiva sin modificar lo existente', async () => { const before = await temp.umlClass.findFirstOrThrow({ where: { name: 'Cliente' } }); const extra = { classes: [{ name: 'Factura', attributes: [], methods: [] }], relations: [] }; const result = await call(applyPath, 'POST', { proposal: extra }, memberToken); assert.equal(result.status, 201); assert.equal(result.data.diagram.classes.length, 3); assert.deepEqual(await temp.umlClass.findUnique({ where: { id: before.id } }), before); });
  await t.test('revalida estado actual, rechaza duplicados y no emite al fallar', async () => { let emitted = false; socket.once('uml:diagram:updated', () => { emitted = true }); assert.equal((await call(applyPath, 'POST', { proposal }, hostToken)).status, 409); await new Promise(resolve => setTimeout(resolve, 100)); assert.equal(emitted, false); assert.equal(await temp.umlClass.count({ where: { diagram: { projectId: project.id } } }), 3); });
  await t.test('atributos, métodos, relaciones y multiplicidades inválidas hacen rollback', async () => { const count = await temp.umlClass.count(); const duplicateAttribute = { classes: [{ name: 'Invalida', attributes: [{ name: 'id', type: 'Long', visibility: 'PRIVATE' }, { name: 'ID', type: 'UUID', visibility: 'PRIVATE' }], methods: [] }], relations: [] }; assert.equal((await call(applyPath, 'POST', { proposal: duplicateAttribute }, hostToken)).status, 400); const duplicateMethod = { classes: [{ name: 'Invalida', attributes: [], methods: [{ name: 'x', returnType: 'void', visibility: 'PUBLIC' }, { name: 'X', returnType: 'void', visibility: 'PUBLIC' }] }], relations: [] }; assert.equal((await call(applyPath, 'POST', { proposal: duplicateMethod }, hostToken)).status, 400); const badRelation = { classes: [{ name: 'Invalida', attributes: [], methods: [] }], relations: [{ sourceClassName: 'Invalida', targetClassName: 'Ausente', type: 'ASSOCIATION' }] }; assert.equal((await call(applyPath, 'POST', { proposal: badRelation }, hostToken)).status, 400); const badMultiplicity = { classes: [{ name: 'Invalida', attributes: [], methods: [] }], relations: [{ sourceClassName: 'Invalida', targetClassName: 'Invalida', type: 'ASSOCIATION', sourceMultiplicity: 'muchos' }] }; assert.equal((await call(applyPath, 'POST', { proposal: badMultiplicity }, hostToken)).status, 400); assert.equal(await temp.umlClass.count(), count); });
 } finally { socket?.disconnect(); if (app) await app.close(); if (temp) await temp.$disconnect(); process.env.DATABASE_URL = originalUrl; if (originalProvider === undefined) delete process.env.AI_PROVIDER; else process.env.AI_PROVIDER = originalProvider; await root.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await root.$disconnect(); }
});
