const { test } = require('node:test'); const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs');
require('reflect-metadata'); process.loadEnvFile('.env');
const { PrismaClient } = require('@prisma/client'); const { NestFactory } = require('@nestjs/core'); const JSZip = require('jszip'); const { PasswordService } = require('../dist/common/security/password.service'); const { configureApplication } = require('../dist/config/configure-app');

test('Fase 4D genera un backend Spring Boot descargable desde el UML', async t => {
 const schema = `arqnova_test_${randomUUID().replaceAll('-', '')}`; const root = new PrismaClient(); let temp; let app; const originalUrl = process.env.DATABASE_URL;
 try {
  await root.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`); const url = new URL(originalUrl); url.searchParams.set('schema', schema); process.env.DATABASE_URL = url.toString(); temp = new PrismaClient({ datasources: { db: { url: url.toString() } } });
  for (const directory of fs.readdirSync('prisma/migrations').sort()) { const migration = `prisma/migrations/${directory}/migration.sql`; if (fs.existsSync(migration)) for (const sql of fs.readFileSync(migration, 'utf8').split(';').map(value => value.trim()).filter(Boolean)) await temp.$executeRawUnsafe(sql); }
  const roles = {}; for (const name of ['ADMINISTRADOR', 'ANFITRION', 'COLABORADOR']) roles[name] = await temp.role.create({ data: { name } }); const passwords = new PasswordService(); const createUser = async role => { const password = randomBytes(24).toString('hex'); const user = await temp.user.create({ data: { name: role, email: `${randomUUID()}@example.test`, passwordHash: await passwords.hash(password), roleId: roles[role].id } }); return { ...user, password }; };
  const host = await createUser('ANFITRION'); const member = await createUser('COLABORADOR'); const outsider = await createUser('COLABORADOR'); const admin = await createUser('ADMINISTRADOR'); const project = await temp.project.create({ data: { name: 'Generación Java', ownerId: host.id, members: { create: { userId: member.id } } } }); const emptyProject = await temp.project.create({ data: { name: 'Vacío', ownerId: host.id } });
  const diagram = await temp.diagram.create({ data: { projectId: project.id, name: 'Ventas Backend', classes: { create: [{ name: 'Persona', x: 0, y: 0, isAbstract: true, attributes: { create: { name: 'id', type: 'Long', visibility: 'PRIVATE', isPrimaryKey: true } } }, { name: 'Cliente', x: 200, y: 0, attributes: { create: [{ name: 'nombre', type: 'String', visibility: 'PRIVATE' }, { name: 'saldo', type: 'Decimal', visibility: 'PRIVATE' }] }, methods: { create: { name: 'registrar', returnType: 'void', visibility: 'PUBLIC' } } }, { name: 'Pedido', x: 400, y: 0, attributes: { create: { name: 'total', type: 'Double', visibility: 'PRIVATE' } } }, { name: 'Direccion', x: 600, y: 0, attributes: { create: { name: 'calle', type: 'String', visibility: 'PRIVATE' } } }] } }, include: { classes: true } }); const byName = Object.fromEntries(diagram.classes.map(item => [item.name, item])); await temp.umlRelation.createMany({ data: [{ diagramId: diagram.id, sourceClassId: byName.Cliente.id, targetClassId: byName.Persona.id, type: 'INHERITANCE', sourceMultiplicity: '1', targetMultiplicity: '1' }, { diagramId: diagram.id, sourceClassId: byName.Cliente.id, targetClassId: byName.Pedido.id, type: 'ASSOCIATION', sourceMultiplicity: '1', targetMultiplicity: '0..*', label: 'pedidos' }, { diagramId: diagram.id, sourceClassId: byName.Cliente.id, targetClassId: byName.Direccion.id, type: 'COMPOSITION', sourceMultiplicity: '1', targetMultiplicity: '1', label: 'direccion' }] });
  const { AppModule } = require('../dist/app.module'); app = await NestFactory.create(AppModule, { logger: false }); configureApplication(app); await app.listen(0, '127.0.0.1'); const base = `${await app.getUrl()}/api`;
  const json = async (path, method, token) => { const response = await fetch(`${base}${path}`, { method, headers: token ? { Authorization: `Bearer ${token}` } : {} }); return { status: response.status, data: await response.json() }; }; const tokenFor = async user => (await fetch(`${base}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: user.email, password: user.password }) }).then(value => value.json())).accessToken; const hostToken = await tokenFor(host); const memberToken = await tokenFor(member); const outsiderToken = await tokenFor(outsider); const adminToken = await tokenFor(admin); const generatePath = `/projects/${project.id}/code-generation/generate`;
  await t.test('anfitrión y colaborador generan manifiesto sin modificar el diagrama', async () => { const before = await temp.umlClass.count(); for (const token of [hostToken, memberToken]) { const result = await json(generatePath, 'POST', token); assert.equal(result.status, 201); assert.equal(result.data.classCount, 4); assert.equal(result.data.fileCount, 24); assert.ok(result.data.files.includes('generated-backend/pom.xml')); assert.ok(result.data.files.includes('generated-backend/src/main/java/com/arqnova/generated/model/Cliente.java')); } assert.equal(await temp.umlClass.count(), before); });
  await t.test('ZIP contiene proyecto Maven y capas Spring Boot', async () => { const response = await fetch(`${base}/projects/${project.id}/code-generation/download`, { headers: { Authorization: `Bearer ${hostToken}` } }); assert.equal(response.status, 200); assert.match(response.headers.get('content-type'), /application\/zip/); assert.match(response.headers.get('content-disposition'), /generated-backend\.zip/); const zip = await JSZip.loadAsync(Buffer.from(await response.arrayBuffer())); const paths = Object.keys(zip.files); for (const required of ['generated-backend/pom.xml', 'generated-backend/src/main/java/com/arqnova/generated/GeneratedBackendApplication.java', 'generated-backend/src/main/java/com/arqnova/generated/controller/ClienteController.java', 'generated-backend/src/main/java/com/arqnova/generated/service/ClienteService.java', 'generated-backend/src/main/java/com/arqnova/generated/repository/ClienteRepository.java', 'generated-backend/src/main/java/com/arqnova/generated/dto/ClienteDto.java']) assert.ok(paths.includes(required), required); const entity = await zip.file('generated-backend/src/main/java/com/arqnova/generated/model/Cliente.java').async('string'); assert.match(entity, /class Cliente extends Persona/); assert.match(entity, /BigDecimal saldo/); assert.match(entity, /List<Pedido> pedidosList/); assert.match(entity, /@OneToMany/); assert.match(entity, /@ManyToOne\(cascade = CascadeType.ALL\)/); assert.match(entity, /public void registrar\(\)/); });
  await t.test('entidades simples, repositorios y configuración son compilables conceptualmente', async () => { const response = await fetch(`${base}/projects/${project.id}/code-generation/download`, { headers: { Authorization: `Bearer ${hostToken}` } }); const zip = await JSZip.loadAsync(Buffer.from(await response.arrayBuffer())); const persona = await zip.file('generated-backend/src/main/java/com/arqnova/generated/model/Persona.java').async('string'); const repository = await zip.file('generated-backend/src/main/java/com/arqnova/generated/repository/PersonaRepository.java').async('string'); const properties = await zip.file('generated-backend/src/main/resources/application.properties').async('string'); assert.match(persona, /@Entity/); assert.match(persona, /@Id/); assert.match(repository, /JpaRepository<Persona, Long>/); assert.match(properties, /DB_URL/); });
  await t.test('JWT, acceso y diagrama no vacío son obligatorios', async () => { assert.equal((await json(generatePath, 'POST')).status, 401); assert.equal((await json(generatePath, 'POST', outsiderToken)).status, 403); assert.equal((await json(generatePath, 'POST', adminToken)).status, 403); await temp.diagram.create({ data: { projectId: emptyProject.id, name: 'Vacío' } }); assert.equal((await json(`/projects/${emptyProject.id}/code-generation/generate`, 'POST', hostToken)).status, 400); });
 } finally { if (app) await app.close(); if (temp) await temp.$disconnect(); process.env.DATABASE_URL = originalUrl; await root.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await root.$disconnect(); }
});
