const { test } = require('node:test'); const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs');
require('reflect-metadata'); process.loadEnvFile('.env'); const { PrismaClient } = require('@prisma/client'); const { NestFactory } = require('@nestjs/core'); const { io } = require('../../frontend/node_modules/socket.io-client'); const { PasswordService } = require('../dist/common/security/password.service'); const { configureApplication } = require('../dist/config/configure-app');

test('CU06 autentica, aísla rooms, sincroniza presencia y controla locks', async t => {
 const schema = `arqnova_test_${randomUUID().replaceAll('-', '')}`; const root = new PrismaClient(); let temp; let app; const sockets = []; const originalUrl = process.env.DATABASE_URL;
 try {
  await root.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`); const url = new URL(originalUrl); url.searchParams.set('schema', schema); process.env.DATABASE_URL = url.toString(); temp = new PrismaClient({ datasources: { db: { url: url.toString() } } });
  for (const directory of fs.readdirSync('prisma/migrations').sort()) { const path = `prisma/migrations/${directory}/migration.sql`; if (fs.existsSync(path)) for (const sql of fs.readFileSync(path, 'utf8').split(';').map(v => v.trim()).filter(Boolean)) await temp.$executeRawUnsafe(sql); }
  const hostRole = await temp.role.create({ data: { name: 'ANFITRION' } }); const collaboratorRole = await temp.role.create({ data: { name: 'COLABORADOR' } }); const passwords = new PasswordService();
  const createUser = async (name, roleId) => { const password = randomBytes(24).toString('hex'); const user = await temp.user.create({ data: { name, email: `${randomUUID()}@example.test`, passwordHash: await passwords.hash(password), roleId } }); return { ...user, password }; };
  const host = await createUser('Anfitrión realtime', hostRole.id); const member = await createUser('Colaborador realtime', collaboratorRole.id); const outsider = await createUser('Externo', collaboratorRole.id);
  const project = await temp.project.create({ data: { name: 'Realtime', ownerId: host.id, members: { create: { userId: member.id } } } }); const otherProject = await temp.project.create({ data: { name: 'Otra room', ownerId: host.id } }); const diagram = await temp.diagram.create({ data: { name: 'Principal', projectId: project.id } }); const umlClass = await temp.umlClass.create({ data: { diagramId: diagram.id, name: 'Cliente', x: 0, y: 0 } });
  const { AppModule } = require('../dist/app.module'); app = await NestFactory.create(AppModule, { logger: false }); configureApplication(app); await app.listen(0, '127.0.0.1'); const base = `${await app.getUrl()}/api`; const socketUrl = `${await app.getUrl()}/collaboration`;
  const request = async (path, method = 'GET', body, token) => { const response = await fetch(`${base}${path}`, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) }); return { status: response.status, data: await response.json() }; };
  const tokenFor = async user => (await request('/auth/login', 'POST', { email: user.email, password: user.password })).data.accessToken; const hostToken = await tokenFor(host); const memberToken = await tokenFor(member); const outsiderToken = await tokenFor(outsider);
  const connect = token => new Promise((resolve, reject) => { const socket = io(socketUrl, { auth: { token }, transports: ['websocket'], forceNew: true }); sockets.push(socket); socket.once('connect', () => resolve(socket)); socket.once('connect_error', reject); });
  const ack = (socket, event, payload) => socket.timeout(3000).emitWithAck(event, payload); const waitEvent = (socket, event) => new Promise(resolve => socket.once(event, resolve));
  let hostSocket; let memberSocket; let otherRoomSocket;
  await t.test('socket anónimo es rechazado y usuario externo no entra al proyecto', async () => { await assert.rejects(connect('')); const external = await connect(outsiderToken); const result = await ack(external, 'project:join', { projectId: project.id }); assert.equal(result.ok, false); assert.equal(result.status, 403); external.disconnect(); });
  await t.test('anfitrión y miembro entran, reciben estado actual y presencia', async () => { hostSocket = await connect(hostToken); memberSocket = await connect(memberToken); let result = await ack(hostSocket, 'project:join', { projectId: project.id }); assert.equal(result.ok, true); assert.equal(result.data.diagram.classes[0].id, umlClass.id); const presenceEvent = waitEvent(hostSocket, 'project:presence'); result = await ack(memberSocket, 'project:join', { projectId: project.id }); assert.equal(result.ok, true); const presence = await presenceEvent; assert.equal(presence.length, 2); });
  await t.test('lock se concede, renueva, bloquea segundo usuario y protege REST', async () => { let result = await ack(hostSocket, 'uml:lock:acquire', { projectId: project.id, elementType: 'UML_CLASS', elementId: umlClass.id }); assert.equal(result.ok, true); const firstExpiry = result.data.expiresAt; result = await ack(hostSocket, 'uml:lock:renew', { projectId: project.id, elementType: 'UML_CLASS', elementId: umlClass.id }); assert.equal(result.ok, true); assert.ok(result.data.expiresAt >= firstExpiry); result = await ack(memberSocket, 'uml:lock:acquire', { projectId: project.id, elementType: 'UML_CLASS', elementId: umlClass.id }); assert.equal(result.ok, false); assert.equal(result.status, 409); assert.equal((await request(`/projects/${project.id}/diagram/classes/${umlClass.id}`, 'PATCH', { name: 'Conflicto' }, memberToken)).status, 409); assert.equal((await ack(hostSocket, 'uml:lock:release', { projectId: project.id, elementType: 'UML_CLASS', elementId: umlClass.id })).data.released, true); });
  await t.test('persistencia ocurre antes del broadcast y otra room no recibe el evento', async () => { otherRoomSocket = await connect(hostToken); await ack(otherRoomSocket, 'project:join', { projectId: otherProject.id }); let leaked = false; otherRoomSocket.once('uml:class:updated', () => { leaked = true }); const eventPromise = waitEvent(hostSocket, 'uml:class:updated'); const response = await request(`/projects/${project.id}/diagram/classes/${umlClass.id}`, 'PATCH', { name: 'Sincronizada' }, memberToken); assert.equal(response.status, 200); const event = await eventPromise; assert.equal(event.diagram.classes.find(item => item.id === umlClass.id).name, 'Sincronizada'); assert.equal((await temp.umlClass.findUniqueOrThrow({ where: { id: umlClass.id } })).name, 'Sincronizada'); await new Promise(resolve => setTimeout(resolve, 100)); assert.equal(leaked, false); });
  await t.test('actualización fallida no emite evento', async () => { let emitted = false; hostSocket.once('uml:class:updated', () => { emitted = true }); assert.equal((await request(`/projects/${project.id}/diagram/classes/${umlClass.id}`, 'PATCH', { name: '' }, memberToken)).status, 400); await new Promise(resolve => setTimeout(resolve, 100)); assert.equal(emitted, false); });
  await t.test('disconnect libera lock y limpia presencia', async () => { let result = await ack(memberSocket, 'uml:lock:acquire', { projectId: project.id, elementType: 'UML_CLASS', elementId: umlClass.id }); assert.equal(result.ok, true); const released = waitEvent(hostSocket, 'uml:lock:released'); const presence = waitEvent(hostSocket, 'project:presence'); memberSocket.disconnect(); assert.equal((await released).elementId, umlClass.id); assert.equal((await presence).length, 1); result = await ack(hostSocket, 'uml:lock:acquire', { projectId: project.id, elementType: 'UML_CLASS', elementId: umlClass.id }); assert.equal(result.ok, true); });
  await t.test('TTL elimina locks huérfanos', async () => { const { CollaborationService } = require('../dist/collaboration/collaboration.service'); const service = app.get(CollaborationService); const lock = service.getLocks(project.id)[0]; lock.expiresAt = new Date(Date.now() - 1).toISOString(); assert.deepEqual(service.getLocks(project.id), []); });
 } finally { for (const socket of sockets) socket.disconnect(); if (app) await app.close(); if (temp) await temp.$disconnect(); process.env.DATABASE_URL = originalUrl; await root.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await root.$disconnect(); }
});
