const { test } = require('node:test'); const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs');
require('reflect-metadata'); process.loadEnvFile('.env');
const { PrismaClient } = require('@prisma/client'); const { NestFactory } = require('@nestjs/core'); const { PasswordService } = require('../dist/common/security/password.service'); const { configureApplication } = require('../dist/config/configure-app');

test('CU05 gestiona el editor UML por HTTP en un esquema aislado', async t => {
 const schema = `arqnova_test_${randomUUID().replaceAll('-', '')}`; const root = new PrismaClient(); let temp; let app; const originalUrl = process.env.DATABASE_URL;
 try {
  await root.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`); const url = new URL(originalUrl); url.searchParams.set('schema', schema); process.env.DATABASE_URL = url.toString(); temp = new PrismaClient({ datasources: { db: { url: url.toString() } } });
  for (const directory of fs.readdirSync('prisma/migrations').sort()) { const path = `prisma/migrations/${directory}/migration.sql`; if (fs.existsSync(path)) for (const sql of fs.readFileSync(path, 'utf8').split(';').map(value => value.trim()).filter(Boolean)) await temp.$executeRawUnsafe(sql); }
  const roles = {}; for (const name of ['ADMINISTRADOR', 'ANFITRION', 'COLABORADOR']) roles[name] = await temp.role.create({ data: { name } }); const passwords = new PasswordService();
  const createUser = async role => { const password = randomBytes(24).toString('hex'); const user = await temp.user.create({ data: { name: role, email: `${randomUUID()}@example.test`, passwordHash: await passwords.hash(password), roleId: roles[role].id } }); return { ...user, password }; };
  const host = await createUser('ANFITRION'); const collaborator = await createUser('COLABORADOR'); const outsider = await createUser('COLABORADOR'); const admin = await createUser('ADMINISTRADOR');
  const project = await temp.project.create({ data: { name: 'Editor CU05', ownerId: host.id, members: { create: { userId: collaborator.id } } } }); const foreignProject = await temp.project.create({ data: { name: 'Externo', ownerId: host.id } });
  const { AppModule } = require('../dist/app.module'); app = await NestFactory.create(AppModule, { logger: false }); configureApplication(app); await app.listen(0, '127.0.0.1'); const base = `${await app.getUrl()}/api`;
  const call = async (path, method = 'GET', body, token) => { const headers = { Accept: 'application/json', 'Content-Type': 'application/json' }; if (token) headers.Authorization = `Bearer ${token}`; const response = await fetch(`${base}${path}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) }); const data = await response.json(); assert.equal(JSON.stringify(data).includes('passwordHash'), false); return { status: response.status, data }; };
  const tokenFor = async user => (await call('/auth/login', 'POST', { email: user.email, password: user.password })).data.accessToken; const hostToken = await tokenFor(host); const memberToken = await tokenFor(collaborator); const outsiderToken = await tokenFor(outsider); const adminToken = await tokenFor(admin); const path = `/projects/${project.id}/diagram`;
  let source; let target; let attribute; let method; const createdRelations = [];
  await t.test('anfitrión crea/carga automáticamente y colaborador miembro accede', async () => { const first = await call(path, 'GET', undefined, hostToken); assert.equal(first.status, 200); assert.equal(first.data.projectId, project.id); const member = await call(path, 'GET', undefined, memberToken); assert.equal(member.status, 200); assert.equal(member.data.id, first.data.id); });
  await t.test('usuario externo, administrador y petición sin token son rechazados', async () => { assert.equal((await call(path, 'GET', undefined, outsiderToken)).status, 403); assert.equal((await call(path, 'GET', undefined, adminToken)).status, 403); assert.equal((await call(path)).status, 401); });
  await t.test('crea, edita y mueve clases con posición persistente', async () => { let result = await call(`${path}/classes`, 'POST', { name: 'Cliente', x: 10, y: 20 }, hostToken); assert.equal(result.status, 201); source = result.data; result = await call(`${path}/classes`, 'POST', { name: 'Pedido', x: 300, y: 100 }, memberToken); target = result.data; assert.equal(result.status, 201); result = await call(`${path}/classes/${source.id}`, 'PATCH', { name: 'ClienteActualizado', isAbstract: true }, memberToken); assert.equal(result.data.isAbstract, true); result = await call(`${path}/classes/${source.id}/position`, 'PATCH', { x: 125.5, y: -45 }, hostToken); assert.equal(result.data.x, 125.5); assert.equal(result.data.y, -45); });
  await t.test('agrega, edita y elimina atributos', async () => { let result = await call(`${path}/classes/${source.id}/attributes`, 'POST', { name: 'id', type: 'Long', visibility: 'PRIVATE', isPrimaryKey: true }, memberToken); attribute = result.data; assert.equal(result.status, 201); result = await call(`${path}/classes/${source.id}/attributes/${attribute.id}`, 'PATCH', { name: 'codigo', type: 'UUID', visibility: 'PUBLIC', isPrimaryKey: false }, hostToken); assert.equal(result.data.type, 'UUID'); const removable = (await call(`${path}/classes/${source.id}/attributes`, 'POST', { name: 'temporal', type: 'String', visibility: 'PRIVATE' }, hostToken)).data; assert.equal((await call(`${path}/classes/${source.id}/attributes/${removable.id}`, 'DELETE', undefined, hostToken)).status, 200); });
  await t.test('agrega, edita y elimina métodos', async () => { let result = await call(`${path}/classes/${source.id}/methods`, 'POST', { name: 'guardar', returnType: 'void', visibility: 'PUBLIC' }, hostToken); method = result.data; assert.equal(result.status, 201); result = await call(`${path}/classes/${source.id}/methods/${method.id}`, 'PATCH', { name: 'persistir', returnType: 'boolean', visibility: 'PROTECTED' }, memberToken); assert.equal(result.data.returnType, 'boolean'); const removable = (await call(`${path}/classes/${source.id}/methods`, 'POST', { name: 'temporal', returnType: 'void', visibility: 'PUBLIC' }, hostToken)).data; assert.equal((await call(`${path}/classes/${source.id}/methods/${removable.id}`, 'DELETE', undefined, hostToken)).status, 200); });
  await t.test('crea todos los tipos de relación y conserva multiplicidades', async () => { for (const type of ['ASSOCIATION', 'AGGREGATION', 'COMPOSITION', 'INHERITANCE', 'DEPENDENCY']) { const result = await call(`${path}/relations`, 'POST', { sourceClassId: source.id, targetClassId: target.id, type, sourceMultiplicity: '0..1', targetMultiplicity: '1..*', label: type }, hostToken); assert.equal(result.status, 201); assert.equal(result.data.targetMultiplicity, '1..*'); createdRelations.push(result.data); } });
  await t.test('edita y elimina relación', async () => { const relation = createdRelations.shift(); let result = await call(`${path}/relations/${relation.id}`, 'PATCH', { type: 'COMPOSITION', sourceMultiplicity: '1', targetMultiplicity: '0..*', label: 'posee' }, memberToken); assert.equal(result.data.label, 'posee'); result = await call(`${path}/relations/${relation.id}`, 'DELETE', undefined, hostToken); assert.equal(result.status, 200); });
  await t.test('impide relaciones cruzadas y elementos bajo URL de otro proyecto', async () => { const foreignDiagram = (await call(`/projects/${foreignProject.id}/diagram`, 'GET', undefined, hostToken)).data; const foreignClass = (await call(`/projects/${foreignProject.id}/diagram/classes`, 'POST', { name: 'Externa', x: 0, y: 0 }, hostToken)).data; assert.equal(foreignClass.diagramId, foreignDiagram.id); assert.equal((await call(`${path}/relations`, 'POST', { sourceClassId: source.id, targetClassId: foreignClass.id, type: 'ASSOCIATION' }, hostToken)).status, 400); assert.equal((await call(`${path}/classes/${foreignClass.id}`, 'PATCH', { name: 'Intrusión' }, hostToken)).status, 404); });
  await t.test('carga completa reconstruye modelo y nunca expone datos sensibles', async () => { const result = await call(path, 'GET', undefined, memberToken); assert.equal(result.status, 200); const loaded = result.data.classes.find(item => item.id === source.id); assert.equal(loaded.name, 'ClienteActualizado'); assert.equal(loaded.x, 125.5); assert.equal(loaded.attributes[0].name, 'codigo'); assert.equal(loaded.methods[0].name, 'persistir'); assert.equal(result.data.relations.length, 4); });
  await t.test('eliminar clase elimina atributos, métodos y relaciones asociadas', async () => { assert.equal((await call(`${path}/classes/${source.id}`, 'DELETE', undefined, memberToken)).status, 200); assert.equal(await temp.umlAttribute.count({ where: { umlClassId: source.id } }), 0); assert.equal(await temp.umlMethod.count({ where: { umlClassId: source.id } }), 0); assert.equal(await temp.umlRelation.count({ where: { OR: [{ sourceClassId: source.id }, { targetClassId: source.id }] } }), 0); });
 } finally { if (app) await app.close(); if (temp) await temp.$disconnect(); process.env.DATABASE_URL = originalUrl; await root.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await root.$disconnect(); }
});
