const { test } = require('node:test'); const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs');
require('reflect-metadata'); process.loadEnvFile('.env');
const { PrismaClient } = require('@prisma/client'); const { NestFactory } = require('@nestjs/core'); const { PasswordService } = require('../dist/common/security/password.service'); const { configureApplication } = require('../dist/config/configure-app');

test('Fase 4C exporta e importa XMI de forma segura y atómica', async t => {
 const schema = `arqnova_test_${randomUUID().replaceAll('-', '')}`; const root = new PrismaClient(); let temp; let app; const originalUrl = process.env.DATABASE_URL;
 try {
  await root.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`); const url = new URL(originalUrl); url.searchParams.set('schema', schema); process.env.DATABASE_URL = url.toString(); temp = new PrismaClient({ datasources: { db: { url: url.toString() } } });
  for (const directory of fs.readdirSync('prisma/migrations').sort()) { const migration = `prisma/migrations/${directory}/migration.sql`; if (fs.existsSync(migration)) for (const sql of fs.readFileSync(migration, 'utf8').split(';').map(value => value.trim()).filter(Boolean)) await temp.$executeRawUnsafe(sql); }
  const roles = {}; for (const name of ['ADMINISTRADOR', 'ANFITRION', 'COLABORADOR']) roles[name] = await temp.role.create({ data: { name } }); const passwords = new PasswordService();
  const createUser = async role => { const password = randomBytes(24).toString('hex'); const user = await temp.user.create({ data: { name: role, email: `${randomUUID()}@example.test`, passwordHash: await passwords.hash(password), roleId: roles[role].id } }); return { ...user, password }; };
  const host = await createUser('ANFITRION'); const member = await createUser('COLABORADOR'); const outsider = await createUser('COLABORADOR'); const source = await temp.project.create({ data: { name: 'Origen XMI', ownerId: host.id, members: { create: { userId: member.id } } } }); const target = await temp.project.create({ data: { name: 'Destino XMI', ownerId: host.id, members: { create: { userId: member.id } } } });
  const diagram = await temp.diagram.create({ data: { projectId: source.id, name: 'Ventas', classes: { create: [{ name: 'Cliente', x: 110, y: 220, attributes: { create: [{ name: 'id', type: 'Long', visibility: 'PRIVATE', isPrimaryKey: true, position: 0 }] }, methods: { create: [{ name: 'registrar', returnType: 'void', visibility: 'PUBLIC', position: 0 }] } }, { name: 'Pedido', x: 430, y: 220 }] } }, include: { classes: true } }); const cliente = diagram.classes.find(item => item.name === 'Cliente'); const pedido = diagram.classes.find(item => item.name === 'Pedido'); await temp.umlRelation.create({ data: { diagramId: diagram.id, sourceClassId: cliente.id, targetClassId: pedido.id, type: 'COMPOSITION', sourceMultiplicity: '1', targetMultiplicity: '0..*', label: 'realiza' } });
  const { AppModule } = require('../dist/app.module'); app = await NestFactory.create(AppModule, { logger: false }); configureApplication(app); await app.listen(0, '127.0.0.1'); const base = `${await app.getUrl()}/api`;
  const json = async (path, method, body, token) => { const response = await fetch(`${base}${path}`, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) }); return { status: response.status, data: await response.json() }; };
  const tokenFor = async user => (await json('/auth/login', 'POST', { email: user.email, password: user.password })).data.accessToken; const hostToken = await tokenFor(host); const memberToken = await tokenFor(member); const outsiderToken = await tokenFor(outsider);
  const exportXmi = async (projectId, token) => fetch(`${base}/projects/${projectId}/xmi/export`, { headers: token ? { Authorization: `Bearer ${token}` } : {} });
  const importXmi = async (projectId, token, content, filename = 'model.xmi') => { const form = new FormData(); form.append('file', new Blob([content], { type: 'application/xml' }), filename); const response = await fetch(`${base}/projects/${projectId}/xmi/import`, { method: 'POST', headers: token ? { Authorization: `Bearer ${token}` } : {}, body: form }); return { status: response.status, data: await response.json() }; };
  let exported;
  await t.test('exporta XMI válido con modelo, clases, atributos, métodos y multiplicidades', async () => { const response = await exportXmi(source.id, hostToken); assert.equal(response.status, 200); assert.match(response.headers.get('content-type'), /application\/xml/); assert.match(response.headers.get('content-disposition'), /Ventas\.xmi/); exported = await response.text(); assert.match(exported, /xmi:XMI/); assert.match(exported, /uml:Model/); assert.match(exported, /Cliente/); assert.match(exported, /ownedAttribute/); assert.match(exported, /ownedOperation/); assert.match(exported, /0\.\.\*/); });
  await t.test('round trip reconstruye el mismo modelo mediante transacción', async () => { const result = await importXmi(target.id, memberToken, exported); assert.equal(result.status, 201, JSON.stringify(result.data)); assert.deepEqual(result.data.imported, { classes: 2, attributes: 1, methods: 1, relations: 1 }); const restored = await temp.diagram.findUniqueOrThrow({ where: { projectId: target.id }, include: { classes: { include: { attributes: true, methods: true } }, relations: true } }); assert.equal(restored.classes.find(item => item.name === 'Cliente').x, 110); assert.equal(restored.classes.find(item => item.name === 'Cliente').attributes[0].isPrimaryKey, true); assert.equal(restored.classes.find(item => item.name === 'Cliente').methods[0].returnType, 'void'); assert.equal(restored.relations[0].type, 'COMPOSITION'); assert.equal(restored.relations[0].targetMultiplicity, '0..*'); });
  await t.test('JWT y acceso al proyecto son obligatorios', async () => { assert.equal((await exportXmi(source.id)).status, 401); assert.equal((await exportXmi(source.id, outsiderToken)).status, 403); assert.equal((await importXmi(target.id, outsiderToken, exported)).status, 403); });
  await t.test('XML inválido y referencias inexistentes se rechazan sin alterar el diagrama', async () => { const before = await temp.diagram.findUniqueOrThrow({ where: { projectId: target.id }, include: { classes: true, relations: true } }); assert.equal((await importXmi(target.id, hostToken, '<xmi:XMI>')).status, 400); const invalidReference = exported.replace(/arqnova:target="class_[^"]+"/, 'arqnova:target="missing"'); assert.equal((await importXmi(target.id, hostToken, invalidReference)).status, 400); const after = await temp.diagram.findUniqueOrThrow({ where: { projectId: target.id }, include: { classes: true, relations: true } }); assert.deepEqual(after.classes.map(item => item.id).sort(), before.classes.map(item => item.id).sort()); assert.deepEqual(after.relations.map(item => item.id), before.relations.map(item => item.id)); });
  await t.test('clases duplicadas se rechazan con rollback completo', async () => { const duplicated = exported.replace('</uml:Model>', `${exported.match(/<packagedElement[^>]*uml:Class[\s\S]*?<\/packagedElement>/)?.[0] ?? ''}</uml:Model>`); const count = await temp.umlClass.count({ where: { diagram: { projectId: target.id } } }); assert.equal((await importXmi(target.id, hostToken, duplicated)).status, 400); assert.equal(await temp.umlClass.count({ where: { diagram: { projectId: target.id } } }), count); });
 } finally { if (app) await app.close(); if (temp) await temp.$disconnect(); process.env.DATABASE_URL = originalUrl; await root.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await root.$disconnect(); }
});
