import { createBrowserRouter } from 'react-router-dom';
import { MainLayout } from '../layouts/MainLayout';
import { HomePage } from '../pages/HomePage';
import { LoginPage } from '../pages/LoginPage';
import { DashboardPage } from '../pages/DashboardPage';
import { NotFoundPage } from '../pages/NotFoundPage';
import { ProtectedRoute } from '../modules/auth/ProtectedRoute';
import { AdminRoute } from '../modules/auth/AdminRoute';
import { AdminUsersPage } from '../pages/AdminUsersPage';
export const router = createBrowserRouter([{ element: <MainLayout/>, children: [{ path: '/', element: <HomePage/> }, { path: '/login', element: <LoginPage/> }, { element: <ProtectedRoute/>, children: [{ path: '/dashboard', element: <DashboardPage/> }, { element: <AdminRoute/>, children: [{ path: '/admin/users', element: <AdminUsersPage/> }] }] }, { path: '*', element: <NotFoundPage/> }] }]);
