const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs'); const path = require('node:path');
process.loadEnvFile(path.resolve('../backend/.env')); process.loadEnvFile(path.resolve('.env')); const tempDir = path.resolve('../.verification/browser-temp'); fs.mkdirSync(tempDir, { recursive: true }); process.env.TEMP = tempDir; process.env.TMP = tempDir;
const { chromium } = require('playwright'); const { PrismaClient } = require('../../backend/node_modules/@prisma/client'); const { PasswordService } = require('../../backend/dist/common/security/password.service'); const WEB = process.env.CORS_ORIGIN; const privateValues = [process.env.ADMIN_PASSWORD, process.env.JWT_SECRET];

(async () => {
 const prisma = new PrismaClient(); let browser; const userIds = []; let project;
 try {
  const roles = Object.fromEntries((await prisma.role.findMany()).map(role => [role.name, role.id])); const createUser = async role => { const password = randomBytes(24).toString('hex'); privateValues.push(password); const user = await prisma.user.create({ data: { name: `IA ${role}`, email: `${randomUUID()}@example.test`, passwordHash: await new PasswordService().hash(password), roleId: roles[role] } }); userIds.push(user.id); return { ...user, password }; };
  const host = await createUser('ANFITRION'); const member = await createUser('COLABORADOR'); const outsider = await createUser('COLABORADOR'); project = await prisma.project.create({ data: { name: `IA-${randomUUID().slice(0, 8)}`, ownerId: host.id, members: { create: { userId: member.id } } } });
  browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true }); const page = await browser.newPage({ viewport: { width: 1280, height: 800 } }); const errors = []; page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) });
  const login = async user => { await page.goto(`${WEB}/login`); await page.getByLabel('Email', { exact: true }).fill(user.email); await page.getByLabel('Contraseña', { exact: true }).fill(user.password); await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click(); await page.waitForURL(`${WEB}/dashboard`) };
  const logout = async () => { await page.goto(`${WEB}/dashboard`); await page.getByRole('button', { name: 'Cerrar sesión' }).click(); await page.waitForURL(`${WEB}/login`) };
  await login(host); await page.goto(`${WEB}/projects/${project.id}`); await page.getByRole('link', { name: 'Describir modelo UML' }).click(); await page.getByRole('heading', { name: 'Propuesta UML mediante IA' }).waitFor(); await page.getByLabel('Describir modelo UML').fill('Crea Cliente y Pedido'); await page.getByRole('button', { name: 'Generar propuesta' }).click(); await page.getByRole('heading', { name: 'Clases' }).waitFor(); await page.getByText('Cliente', { exact: true }).waitFor(); await page.getByText('Pedido', { exact: true }).waitFor(); await page.getByText(/Cliente \[1\].*Pedido \[0\.\.\*\]/).waitFor(); assert.equal(await prisma.diagram.count({ where: { projectId: project.id } }), 0); console.log('ANFITRION genera y visualiza propuesta mock sin modificar el diagrama.');
  await logout(); await login(member); await page.goto(`${WEB}/shared-projects`); await page.getByRole('link', { name: 'Describir modelo UML' }).click(); await page.getByRole('heading', { name: 'Propuesta UML mediante IA' }).waitFor(); console.log('COLABORADOR miembro accede al generador de propuestas.');
  await logout(); await login(outsider); await page.goto(`${WEB}/projects/${project.id}/ai-proposal`); await page.getByLabel('Describir modelo UML').fill('modelo'); await page.getByRole('button', { name: 'Generar propuesta' }).click(); await page.getByRole('alert').filter({ hasText: 'No tienes permiso' }).waitFor(); console.log('Usuario externo recibe acceso denegado por el backend.');
  await page.route(`**/api/projects/${project.id}/ai/uml-proposal`, route => route.abort()); await page.getByRole('button', { name: 'Generar propuesta' }).click(); await page.getByRole('alert').filter({ hasText: 'No se pudo contactar' }).waitFor(); assert.deepEqual(errors, []); console.log('Errores controlados, propuesta solo visual y consola sin errores.');
 } finally { if (project) await prisma.project.deleteMany({ where: { id: project.id } }); if (userIds.length) await prisma.user.deleteMany({ where: { id: { in: userIds } } }); await prisma.$disconnect(); if (browser) await browser.close(); }
})().catch(error => { let message = error.message; for (const value of privateValues.filter(Boolean)) message = message.split(value).join('[REDACTADO]'); console.error('Prueba Fase 4A frontend falló:', message); process.exitCode = 1 });
