const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs'); const path = require('node:path');
process.loadEnvFile(path.resolve('../backend/.env')); process.loadEnvFile(path.resolve('.env')); const tempDir = path.resolve('../.verification/browser-temp'); fs.mkdirSync(tempDir, { recursive: true }); process.env.TEMP = tempDir; process.env.TMP = tempDir;
const { chromium } = require('playwright'); const { PrismaClient } = require('../../backend/node_modules/@prisma/client'); const { PasswordService } = require('../../backend/dist/common/security/password.service'); const WEB = process.env.CORS_ORIGIN; const privateValues = [process.env.ADMIN_PASSWORD, process.env.JWT_SECRET];

(async () => {
 const prisma = new PrismaClient(); let browser; let project; const userIds = [];
 try {
  const roles = Object.fromEntries((await prisma.role.findMany()).map(role => [role.name, role.id])); const createUser = async (role, name) => { const password = randomBytes(24).toString('hex'); privateValues.push(password); const user = await prisma.user.create({ data: { name, email: `${randomUUID()}@example.test`, passwordHash: await new PasswordService().hash(password), roleId: roles[role] } }); userIds.push(user.id); return { ...user, password }; };
  const host = await createUser('ANFITRION', 'Anfitrión IA'); const member = await createUser('COLABORADOR', 'Colaborador IA'); project = await prisma.project.create({ data: { name: `CU07-${randomUUID().slice(0, 8)}`, ownerId: host.id, members: { create: { userId: member.id } } } });
  browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true }); const contextA = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const contextB = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const pageA = await contextA.newPage(); const pageB = await contextB.newPage(); const errors = [];
  for (const page of [pageA, pageB]) { page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) }); }
  const login = async (page, user) => { await page.goto(`${WEB}/login`); await page.getByLabel('Email', { exact: true }).fill(user.email); await page.getByLabel('Contraseña', { exact: true }).fill(user.password); await page.getByRole('button', { name: 'Iniciar sesión' }).click(); await page.waitForURL(`${WEB}/dashboard`); };
  await Promise.all([login(pageA, host), login(pageB, member)]); await pageB.goto(`${WEB}/projects/${project.id}/editor`); await pageB.getByText('Realtime: conectado').waitFor();
  await pageA.goto(`${WEB}/projects/${project.id}/ai-proposal`); const prompt = 'Crea una clase Cliente con id Long, nombre String y correo String. Crea una clase Pedido con id Long, fecha Date y total Decimal. Un Cliente puede tener muchos Pedidos.'; await pageA.getByLabel('Describir modelo UML').fill(prompt); await pageA.getByRole('button', { name: 'Generar propuesta' }).click(); await pageA.getByRole('button', { name: 'Aplicar al diagrama' }).waitFor(); await pageA.getByText('Cliente', { exact: true }).waitFor(); await pageA.getByText(/Cliente \[1\].*Pedido \[0\.\.\*\]/).waitFor();
  await pageA.getByRole('button', { name: 'Cancelar' }).click(); assert.equal(await pageA.getByRole('button', { name: 'Aplicar al diagrama' }).count(), 0); assert.equal(await prisma.umlClass.count({ where: { diagram: { projectId: project.id } } }), 0); console.log('Cancelar descarta la propuesta sin modificar el diagrama.');
  await pageA.getByRole('button', { name: 'Generar propuesta' }).click(); await pageA.getByRole('button', { name: 'Aplicar al diagrama' }).waitFor(); await pageA.getByRole('button', { name: 'Aplicar al diagrama' }).click(); await pageA.getByText('Propuesta aplicada y persistida correctamente.').waitFor(); await pageB.locator('.react-flow__node').filter({ hasText: 'Cliente' }).waitFor(); await pageB.locator('.react-flow__node').filter({ hasText: 'Pedido' }).waitFor(); await pageB.getByRole('button', { name: 'realiza' }).waitFor(); console.log('La segunda sesión recibió clases y relación sin recargar.');
  await pageA.getByRole('link', { name: 'Ver en editor UML' }).click(); await pageA.waitForURL(`${WEB}/projects/${project.id}/editor`); await pageA.locator('.react-flow__node').filter({ hasText: 'correo: String' }).waitFor(); await pageA.locator('.react-flow__node').filter({ hasText: 'total: Decimal' }).waitFor(); await pageA.reload(); await pageA.getByText('Realtime: conectado').waitFor(); await pageA.locator('.react-flow__node').filter({ hasText: 'Cliente' }).waitFor(); assert.equal(await prisma.umlClass.count({ where: { diagram: { projectId: project.id } } }), 2); assert.equal(await prisma.umlRelation.count({ where: { diagram: { projectId: project.id } } }), 1); assert.deepEqual(errors, []); console.log('Editor y recarga reconstruyen el modelo persistido sin errores JavaScript.');
 } finally { if (project) { await prisma.diagram.deleteMany({ where: { projectId: project.id } }); await prisma.project.deleteMany({ where: { id: project.id } }); } if (userIds.length) await prisma.user.deleteMany({ where: { id: { in: userIds } } }); await prisma.$disconnect(); if (browser) await browser.close(); }
})().catch(error => { let message = error.message; for (const value of privateValues.filter(Boolean)) message = message.split(value).join('[REDACTADO]'); console.error('Prueba CU07 frontend falló:', message); process.exitCode = 1; });
