const assert = require('node:assert/strict');
const { randomBytes, randomUUID } = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
process.loadEnvFile(path.resolve('../backend/.env'));
process.loadEnvFile(path.resolve('.env'));
const { chromium } = require('playwright');
const { PrismaClient } = require('../../backend/node_modules/@prisma/client');
const { JwtService } = require('../../backend/node_modules/@nestjs/jwt');
const { PasswordService } = require('../../backend/dist/common/security/password.service');
const API_URL = process.env.VITE_API_URL;
const WEB_URL = process.env.CORS_ORIGIN;
const KEY = 'arqnova.auth.token';
const privateValues = [process.env.ADMIN_PASSWORD, process.env.JWT_SECRET];
const tempDirectory = path.resolve('../.verification/browser-temp');
fs.mkdirSync(tempDirectory, { recursive: true });
process.env.TEMP = tempDirectory; process.env.TMP = tempDirectory;

(async () => {
 const prisma = new PrismaClient(); const ids = [];
 const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
 const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
 const page = await context.newPage(); const errors = [];
 page.on('pageerror', error => errors.push(error.message));
 page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()); });
 const atLogin = async () => { await page.waitForURL(`${WEB_URL}/login`); await page.getByRole('heading', { name: 'Iniciar sesión', exact: true }).waitFor(); };
 const atDashboard = async () => { await page.waitForURL(`${WEB_URL}/dashboard`); await page.getByRole('heading', { name: 'Dashboard', exact: true }).waitFor(); };
 const fill = async (email, password) => { await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Contraseña', { exact: true }).fill(password); };
 const submit = () => page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
 const token = () => page.evaluate(key => localStorage.getItem(key), KEY);
 try {
   await page.goto(`${WEB_URL}/dashboard`); await atLogin(); assert.equal(await token(), null);
   console.log('Dashboard sin sesión redirige a login; formulario responsive carga.');
   await fill(process.env.ADMIN_EMAIL, randomBytes(24).toString('hex')); await submit();
   await page.getByRole('alert').filter({ hasText: 'Credenciales inválidas' }).waitFor(); assert.equal(await token(), null);
   console.log('Credenciales incorrectas: error controlado y sin sesión.');
   await fill(process.env.ADMIN_EMAIL, process.env.ADMIN_PASSWORD); await submit(); await atDashboard();
   await page.getByText(`Email: ${process.env.ADMIN_EMAIL}`, { exact: true }).waitFor();
   await page.getByText('Rol: ADMINISTRADOR', { exact: true }).waitFor();
   const validToken = await token(); privateValues.push(validToken); assert.equal(typeof validToken, 'string');
   const keys = await page.evaluate(() => Object.keys(localStorage)); assert.deepEqual(keys, [KEY]);
   await page.getByText('Backend: arqnova-api: ok', { exact: true }).waitFor();
   await page.getByText('Servidor realtime: conectado', { exact: true }).waitFor();
   console.log('Login real: dashboard, datos públicos, health y Socket.IO OK; solo token almacenado.');
   const meResponse = page.waitForResponse(response => response.url() === `${API_URL}/auth/me` && response.status() === 200);
   await page.reload(); await meResponse; await atDashboard(); assert.equal(await token() === validToken, true);
   await page.goto(`${WEB_URL}/login`); await atDashboard();
   console.log('Recarga recupera sesión mediante /auth/me; login autenticado redirige al dashboard.');
   await page.getByRole('button', { name: 'Cerrar sesión' }).click(); await atLogin(); assert.equal(await token(), null);
   await page.goto(`${WEB_URL}/dashboard`); await atLogin();
   console.log('Logout borra sesión y dashboard deja de ser accesible.');
   for (const value of ['token-invalido', new JwtService({ secret: process.env.JWT_SECRET, signOptions: { algorithm: 'HS256' } }).sign({ sub: (await prisma.user.findUniqueOrThrow({ where: { email: process.env.ADMIN_EMAIL } })).id }, { expiresIn: -1 })]) {
     privateValues.push(value);
     await page.evaluate(({ key, value }) => localStorage.setItem(key, value), { key: KEY, value });
     await page.goto(`${WEB_URL}/dashboard`); await atLogin(); assert.equal(await token(), null);
     await page.getByRole('alert').filter({ hasText: 'Sesión inválida o expirada' }).waitFor();
   }
   console.log('JWT inválido o expirado: limpia almacenamiento y vuelve a login.');
   const role = await prisma.role.findUniqueOrThrow({ where: { name: 'COLABORADOR' } });
   const inactivePassword = randomBytes(24).toString('hex'); privateValues.push(inactivePassword);
   const inactive = await prisma.user.create({ data: { name: 'Prueba browser inactiva', email: `${randomUUID()}@example.test`, passwordHash: await new PasswordService().hash(inactivePassword), roleId: role.id, isActive: false } });
   ids.push(inactive.id);
   await fill(inactive.email, inactivePassword); await submit();
   await page.getByRole('alert').filter({ hasText: 'Credenciales inválidas' }).waitFor(); assert.equal(await token(), null);
   console.log('Usuario inactivo: acceso rechazado sin revelar datos.');
   await page.route(`${API_URL}/auth/login`, route => route.abort('connectionrefused'));
   await fill(process.env.ADMIN_EMAIL, process.env.ADMIN_PASSWORD); await submit();
   await page.getByRole('alert').filter({ hasText: 'No se pudo contactar' }).waitFor();
   await page.unroute(`${API_URL}/auth/login`);
   await page.route(`${API_URL}/auth/login`, route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ internal: 'no debe mostrarse' }) }));
   await fill(process.env.ADMIN_EMAIL, process.env.ADMIN_PASSWORD); await submit();
   await page.getByRole('alert').filter({ hasText: 'Ocurrió un error' }).waitFor();
   assert.equal(await page.getByText('no debe mostrarse').count(), 0);
   await page.unroute(`${API_URL}/auth/login`);
   console.log('API no disponible y error inesperado: mensajes controlados sin detalles internos.');
   let requests = 0;
   await page.route(`${API_URL}/auth/login`, async route => { requests++; await new Promise(resolve => setTimeout(resolve, 700)); await route.continue(); });
   await fill(process.env.ADMIN_EMAIL, process.env.ADMIN_PASSWORD); await submit();
   await page.getByRole('button', { name: 'Iniciando sesión…' }).waitFor();
   assert.equal(await page.getByRole('button', { name: 'Iniciando sesión…' }).isDisabled(), true);
   await page.locator('form').evaluate(form => { form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })); });
   await atDashboard(); assert.equal(requests, 1); await page.unroute(`${API_URL}/auth/login`);
   const liveToken = await token(); privateValues.push(liveToken);
   await page.route(`${API_URL}/auth/me`, route => route.abort('connectionrefused'));
   await page.reload(); await page.getByRole('alert').filter({ hasText: 'No se pudo contactar' }).waitFor();
   assert.equal(await token() === liveToken, true);
   await page.unroute(`${API_URL}/auth/me`); await page.getByRole('button', { name: 'Reintentar', exact: true }).click(); await atDashboard();
   console.log('Envío simultáneo bloqueado; fallo de red al recuperar sesión permite reintentar sin perder token.');
   await page.route(`${API_URL}/auth/me`, route => route.fulfill({ status: 401, contentType: 'application/json', body: '{}' }));
   await page.reload(); await atLogin(); assert.equal(await token(), null); await page.unroute(`${API_URL}/auth/me`);
   assert.deepEqual(errors, []);
   console.log('401 limpia sesión; cero errores JavaScript o React en consola.');
 } finally {
   if (ids.length) await prisma.user.deleteMany({ where: { id: { in: ids } } });
   await prisma.$disconnect(); await context.close(); await browser.close();
 }
})().catch(error => {
 let message = error.message;
 for (const value of privateValues.filter(Boolean)) message = message.split(value).join('[REDACTADO]');
 console.error('Prueba de navegador falló:', message); process.exitCode = 1;
});
