const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs'); const path = require('node:path');
process.loadEnvFile(path.resolve('../backend/.env')); process.loadEnvFile(path.resolve('.env')); const tempDir = path.resolve('../.verification/browser-temp'); fs.mkdirSync(tempDir, { recursive: true }); process.env.TEMP = tempDir; process.env.TMP = tempDir;
const { chromium } = require('playwright'); const JSZip = require('../../backend/node_modules/jszip'); const { PrismaClient } = require('../../backend/node_modules/@prisma/client'); const { PasswordService } = require('../../backend/dist/common/security/password.service'); const WEB = process.env.CORS_ORIGIN; const privateValues = [process.env.ADMIN_PASSWORD, process.env.JWT_SECRET];

(async () => {
 const prisma = new PrismaClient(); let browser; let project; let downloadPath; const userIds = [];
 try {
  const roles = Object.fromEntries((await prisma.role.findMany()).map(role => [role.name, role.id])); const password = randomBytes(24).toString('hex'); privateValues.push(password); const host = await prisma.user.create({ data: { name: 'Anfitrión Generador', email: `${randomUUID()}@example.test`, passwordHash: await new PasswordService().hash(password), roleId: roles.ANFITRION } }); userIds.push(host.id); project = await prisma.project.create({ data: { name: `Generator-${randomUUID().slice(0, 8)}`, ownerId: host.id } }); const diagram = await prisma.diagram.create({ data: { projectId: project.id, name: 'Tienda', classes: { create: { name: 'Producto', x: 80, y: 80, attributes: { create: [{ name: 'id', type: 'Long', visibility: 'PRIVATE', isPrimaryKey: true }, { name: 'nombre', type: 'String', visibility: 'PRIVATE' }, { name: 'precio', type: 'Double', visibility: 'PRIVATE' }] }, methods: { create: { name: 'actualizar', returnType: 'void', visibility: 'PUBLIC' } } } } } });
  browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true }); const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, acceptDownloads: true }); const errors = []; page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) });
  await page.goto(`${WEB}/login`); await page.getByLabel('Email', { exact: true }).fill(host.email); await page.getByLabel('Contraseña', { exact: true }).fill(password); await page.getByRole('button', { name: 'Iniciar sesión' }).click(); await page.waitForURL(`${WEB}/dashboard`); await page.goto(`${WEB}/projects/${project.id}/editor`); await page.getByText('Realtime: conectado').waitFor();
  await page.getByRole('button', { name: 'Generar Backend' }).click(); await page.getByText('Backend generado: 1 clases y 10 archivos.').waitFor(); await page.getByRole('button', { name: 'Descargar ZIP' }).waitFor(); console.log('El editor solicita generación y muestra el resultado.');
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Descargar ZIP' }).click(); const download = await downloadPromise; assert.equal(download.suggestedFilename(), 'generated-backend.zip'); downloadPath = path.join(tempDir, `generated-${randomUUID()}.zip`); await download.saveAs(downloadPath); const zip = await JSZip.loadAsync(fs.readFileSync(downloadPath)); assert.ok(zip.file('generated-backend/pom.xml')); const entity = await zip.file('generated-backend/src/main/java/com/arqnova/generated/model/Producto.java').async('string'); assert.match(entity, /class Producto/); assert.match(entity, /Double precio/); assert.match(entity, /public void actualizar\(\)/); await page.getByText('Backend Spring Boot descargado.').waitFor(); assert.deepEqual(errors, []); console.log('La descarga contiene el proyecto Spring Boot y la consola permanece sin errores.');
  if (downloadPath && fs.existsSync(downloadPath)) fs.unlinkSync(downloadPath);
 } finally { if (project) { await prisma.diagram.deleteMany({ where: { projectId: project.id } }); await prisma.project.deleteMany({ where: { id: project.id } }); } if (userIds.length) await prisma.user.deleteMany({ where: { id: { in: userIds } } }); await prisma.$disconnect(); if (browser) await browser.close(); }
})().catch(error => { let message = error.message; for (const value of privateValues.filter(Boolean)) message = message.split(value).join('[REDACTADO]'); console.error('Prueba frontend del generador falló:', message); process.exitCode = 1; });
