const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs'); const path = require('node:path');
process.loadEnvFile(path.resolve('../backend/.env')); process.loadEnvFile(path.resolve('.env')); const tempDir = path.resolve('../.verification/browser-temp'); fs.mkdirSync(tempDir, { recursive: true }); process.env.TEMP = tempDir; process.env.TMP = tempDir;
const { chromium } = require('playwright'); const { PrismaClient } = require('../../backend/node_modules/@prisma/client'); const { PasswordService } = require('../../backend/dist/common/security/password.service'); const WEB = process.env.CORS_ORIGIN; const privateValues = [process.env.ADMIN_PASSWORD, process.env.JWT_SECRET];

(async () => {
 const prisma = new PrismaClient(); let browser; let project; const userIds = [];
 try {
  const roles = Object.fromEntries((await prisma.role.findMany()).map(role => [role.name, role.id])); const createUser = async (role, name) => { const password = randomBytes(24).toString('hex'); privateValues.push(password); const user = await prisma.user.create({ data: { name, email: `${randomUUID()}@example.test`, passwordHash: await new PasswordService().hash(password), roleId: roles[role] } }); userIds.push(user.id); return { ...user, password }; };
  const host = await createUser('ANFITRION', 'Ana Anfitriona'); const member = await createUser('COLABORADOR', 'Carlos Colaborador'); project = await prisma.project.create({ data: { name: `Realtime-${randomUUID().slice(0, 8)}`, ownerId: host.id, members: { create: { userId: member.id } } } });
  browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true }); const contextA = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const contextB = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const pageA = await contextA.newPage(); const pageB = await contextB.newPage(); const errors = [];
  for (const page of [pageA, pageB]) { page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) }); page.on('dialog', dialog => dialog.accept()); }
  const login = async (page, user) => { await page.goto(`${WEB}/login`); await page.getByLabel('Email', { exact: true }).fill(user.email); await page.getByLabel('Contraseña', { exact: true }).fill(user.password); await page.getByRole('button', { name: 'Iniciar sesión' }).click(); await page.waitForURL(`${WEB}/dashboard`); await page.goto(`${WEB}/projects/${project.id}/editor`); await page.getByText('Realtime: conectado').waitFor(); };
  await Promise.all([login(pageA, host), login(pageB, member)]); await pageA.getByText('Carlos Colaborador · COLABORADOR').waitFor(); await pageB.getByText('Ana Anfitriona · ANFITRION').waitFor(); console.log('Dos sesiones autenticadas comparten presencia en la room del proyecto.');
  await pageA.getByRole('button', { name: 'Nueva clase' }).click(); await pageA.locator('.react-flow__node').filter({ hasText: 'NuevaClase1' }).waitFor(); await pageA.getByLabel('Nombre de clase').fill('ClienteRealtime'); await pageA.getByRole('button', { name: 'Guardar clase' }).click(); await pageB.locator('.react-flow__node').filter({ hasText: 'ClienteRealtime' }).waitFor(); console.log('Clase creada por anfitrión aparece al colaborador sin recargar.');
  await pageA.locator('.react-flow__node').filter({ hasText: 'ClienteRealtime' }).click(); await pageB.getByText('Editando: Ana Anfitriona').waitFor(); await pageB.locator('.react-flow__node').filter({ hasText: 'ClienteRealtime' }).click(); await pageB.getByRole('alert').filter({ hasText: 'Editando: Ana Anfitriona' }).waitFor(); assert.equal(await pageB.getByLabel('Nombre de clase').count(), 0);
  await pageA.getByLabel('Nombre de atributo').fill('email'); await pageA.getByLabel('Tipo de atributo').fill('String'); await pageA.getByRole('button', { name: 'Agregar atributo' }).click(); await pageB.locator('.react-flow__node').filter({ hasText: 'ClienteRealtime' }).getByText('email: String', { exact: false }).waitFor(); await pageA.getByRole('button', { name: 'Cerrar' }).click(); await pageB.getByText('Editando: Ana Anfitriona').waitFor({ state: 'detached' }); console.log('Lock bloquea edición simultánea, cambio de atributo se sincroniza y liberación habilita al segundo usuario.');
  const nodeB = pageB.locator('.react-flow__node').filter({ hasText: 'ClienteRealtime' }); const before = await nodeB.boundingBox(); await pageB.mouse.move(before.x + 60, before.y + 20); await pageB.mouse.down(); await pageB.mouse.move(before.x + 220, before.y + 140, { steps: 8 }); await pageB.mouse.up(); await pageB.getByText('Posición guardada.').waitFor(); const moved = await prisma.umlClass.findFirstOrThrow({ where: { diagram: { projectId: project.id }, name: 'ClienteRealtime' } }); assert.notEqual(moved.x, 80); await pageA.waitForTimeout(300); const nodeAStyle = await pageA.locator('.react-flow__node').filter({ hasText: 'ClienteRealtime' }).getAttribute('style'); assert.match(nodeAStyle, /translate/); console.log('Movimiento del colaborador persiste y se transmite al anfitrión.');
  await pageA.getByRole('button', { name: 'Nueva clase' }).click(); await pageA.locator('.react-flow__node').filter({ hasText: 'NuevaClase2' }).waitFor(); await pageA.getByLabel('Nombre de clase').fill('PedidoRealtime'); await pageA.getByRole('button', { name: 'Guardar clase' }).click(); await pageA.getByRole('button', { name: 'Cerrar' }).click(); await pageB.locator('.react-flow__node').filter({ hasText: 'PedidoRealtime' }).waitFor();
  await pageB.getByRole('button', { name: 'Nueva relación' }).click(); await pageB.getByLabel('Clase de origen').selectOption({ label: 'ClienteRealtime' }); await pageB.getByLabel('Clase de destino').selectOption({ label: 'PedidoRealtime' }); await pageB.getByLabel('Tipo de relación').selectOption('ASSOCIATION'); await pageB.getByLabel('Etiqueta de relación').fill('sincroniza'); await pageB.getByRole('button', { name: 'Crear relación' }).click(); await pageA.getByRole('button', { name: 'sincroniza' }).waitFor(); console.log('Relación creada por colaborador aparece al anfitrión sin recargar.');
  await pageB.reload(); await pageB.getByText('Realtime: conectado').waitFor(); await pageB.getByText('Ana Anfitriona · ANFITRION').waitFor(); await pageB.locator('.react-flow__node').filter({ hasText: 'ClienteRealtime' }).waitFor(); assert.deepEqual(errors, []); console.log('Reconexión vuelve a room, recupera presencia y estado persistido sin errores de consola.');
 } finally { if (project) { await prisma.diagram.deleteMany({ where: { projectId: project.id } }); await prisma.project.deleteMany({ where: { id: project.id } }) } if (userIds.length) await prisma.user.deleteMany({ where: { id: { in: userIds } } }); await prisma.$disconnect(); if (browser) await browser.close(); }
})().catch(error => { let message = error.message; for (const value of privateValues.filter(Boolean)) message = message.split(value).join('[REDACTADO]'); console.error('Prueba CU06 frontend falló:', message); process.exitCode = 1 });
