const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs'); const path = require('node:path');
process.loadEnvFile(path.resolve('../backend/.env')); process.loadEnvFile(path.resolve('.env')); const tempDir = path.resolve('../.verification/browser-temp'); fs.mkdirSync(tempDir, { recursive: true }); process.env.TEMP = tempDir; process.env.TMP = tempDir;
const { chromium } = require('playwright'); const { PrismaClient } = require('../../backend/node_modules/@prisma/client'); const { PasswordService } = require('../../backend/dist/common/security/password.service'); const WEB = process.env.CORS_ORIGIN; const privateValues = [process.env.ADMIN_PASSWORD, process.env.JWT_SECRET];

(async () => {
 const prisma = new PrismaClient(); let browser; const userIds = []; let project;
 try {
  const roles = Object.fromEntries((await prisma.role.findMany()).map(role => [role.name, role.id])); const createUser = async role => { const password = randomBytes(24).toString('hex'); privateValues.push(password); const user = await prisma.user.create({ data: { name: `Editor ${role}`, email: `${randomUUID()}@example.test`, passwordHash: await new PasswordService().hash(password), roleId: roles[role] } }); userIds.push(user.id); return { ...user, password }; };
  const host = await createUser('ANFITRION'); const collaborator = await createUser('COLABORADOR'); const outsider = await createUser('COLABORADOR'); project = await prisma.project.create({ data: { name: `UML-${randomUUID().slice(0, 8)}`, ownerId: host.id, members: { create: { userId: collaborator.id } } } });
  browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true }); const page = await browser.newPage({ viewport: { width: 1440, height: 900 } }); const errors = []; page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) }); page.on('dialog', dialog => dialog.accept());
  const login = async user => { await page.goto(`${WEB}/login`); await page.getByLabel('Email', { exact: true }).fill(user.email); await page.getByLabel('Contraseña', { exact: true }).fill(user.password); await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click(); await page.waitForURL(`${WEB}/dashboard`) };
  const logout = async () => { await page.goto(`${WEB}/dashboard`); await page.getByRole('button', { name: 'Cerrar sesión' }).click(); await page.waitForURL(`${WEB}/login`) };
  await login(host); await page.goto(`${WEB}/projects/${project.id}/editor`); await page.getByRole('heading', { name: /Editor UML/ }).waitFor(); await page.getByText('El diagrama está vacío. Crea tu primera clase.').waitFor();
  await page.getByRole('button', { name: 'Nueva clase' }).click(); await page.locator('.react-flow__node').filter({ hasText: 'NuevaClase1' }).waitFor(); await page.getByLabel('Nombre de clase').fill('Cliente'); await page.getByRole('button', { name: 'Guardar clase' }).click(); await page.locator('.react-flow__node').filter({ hasText: 'Cliente' }).waitFor();
  await page.getByLabel('Nombre de atributo').fill('id'); await page.getByLabel('Tipo de atributo').fill('Long'); await page.getByText('Clave primaria').click(); await page.getByRole('button', { name: 'Agregar atributo' }).click();
  await page.getByLabel('Nombre de método').fill('registrar'); await page.getByLabel('Tipo de retorno').fill('void'); await page.getByRole('button', { name: 'Agregar método' }).click();
  await page.getByRole('button', { name: 'Nueva clase' }).click(); await page.locator('.react-flow__node').filter({ hasText: 'NuevaClase2' }).waitFor(); await page.getByLabel('Nombre de clase').fill('Pedido'); await page.getByRole('button', { name: 'Guardar clase' }).click(); await page.locator('.react-flow__node').filter({ hasText: 'Pedido' }).waitFor();
  const clienteNode = page.locator('.react-flow__node').filter({ hasText: 'Cliente' }); const before = await clienteNode.boundingBox(); assert.ok(before); await page.mouse.move(before.x + 50, before.y + 20); await page.mouse.down(); await page.mouse.move(before.x + 180, before.y + 120, { steps: 8 }); await page.mouse.up(); await page.getByText('Posición guardada.').waitFor();
  await page.getByRole('button', { name: 'Nueva relación' }).click(); await page.getByLabel('Clase de origen').selectOption({ label: 'Cliente' }); await page.getByLabel('Clase de destino').selectOption({ label: 'Pedido' }); await page.getByLabel('Tipo de relación').selectOption('COMPOSITION'); await page.getByLabel('Multiplicidad de origen').selectOption('1'); await page.getByLabel('Multiplicidad de destino').selectOption('0..*'); await page.getByLabel('Etiqueta de relación').fill('realiza'); await page.getByRole('button', { name: 'Crear relación' }).click(); await page.getByText('Relación creada.').waitFor();
  await page.reload(); await page.getByRole('heading', { name: /Editor UML/ }).waitFor(); await page.locator('.react-flow__node').filter({ hasText: 'Cliente' }).getByText('id: Long', { exact: false }).waitFor(); await page.locator('.react-flow__node').filter({ hasText: 'Cliente' }).getByText('registrar(): void', { exact: false }).waitFor(); const edgeLabel = page.locator('.react-flow__edge-text').first(); await edgeLabel.waitFor(); assert.match(await edgeLabel.textContent(), /1\s+realiza\s+0\.\.\*/);
  const persisted = await prisma.umlClass.findFirstOrThrow({ where: { diagram: { projectId: project.id }, name: 'Cliente' } }); assert.notEqual(persisted.x, 80); assert.notEqual(persisted.y, 80); console.log('Clases, posición, atributo, método, relación y multiplicidades reaparecen tras recarga.');
  await page.getByRole('button', { name: 'realiza' }).click(); await page.getByLabel('Tipo de relación').selectOption('AGGREGATION'); await page.getByLabel('Etiqueta de relación').fill('agrupa'); await page.getByRole('button', { name: 'Guardar relación' }).click(); await page.getByText('Relación actualizada.').waitFor(); await page.getByRole('button', { name: 'agrupa' }).click(); await page.getByRole('button', { name: 'Eliminar relación' }).click(); await page.getByText('Relación eliminada.').waitFor();
  await page.locator('.react-flow__node').filter({ hasText: 'Pedido' }).click(); await page.getByRole('button', { name: 'Eliminar clase' }).click(); await page.getByText('Clase eliminada.').waitFor(); assert.equal(await prisma.umlClass.count({ where: { diagram: { projectId: project.id } } }), 1); console.log('Edición/eliminación de relación y eliminación de clase funcionan.');
  await logout(); await login(collaborator); await page.goto(`${WEB}/shared-projects`); await page.getByRole('link', { name: 'Abrir editor UML' }).click(); await page.getByRole('heading', { name: /Editor UML/ }).waitFor(); await page.getByRole('button', { name: 'Nueva clase' }).waitFor(); console.log('COLABORADOR miembro abre el editor desde proyectos compartidos.');
  await logout(); await login(outsider); await page.goto(`${WEB}/projects/${project.id}/editor`); await page.waitForURL(`${WEB}/dashboard`); assert.deepEqual(errors, []); console.log('Usuario externo es bloqueado por backend; consola JavaScript sin errores.');
 } finally { if (project) { await prisma.diagram.deleteMany({ where: { projectId: project.id } }); await prisma.project.deleteMany({ where: { id: project.id } }) } if (userIds.length) await prisma.user.deleteMany({ where: { id: { in: userIds } } }); await prisma.$disconnect(); if (browser) await browser.close(); }
})().catch(error => { let message = error.message; for (const value of privateValues.filter(Boolean)) message = message.split(value).join('[REDACTADO]'); console.error('Prueba CU05 frontend falló:', message); process.exitCode = 1 });
