const assert = require('node:assert/strict'); const { randomBytes, randomUUID } = require('node:crypto'); const fs = require('node:fs'); const path = require('node:path');
process.loadEnvFile(path.resolve('../backend/.env')); process.loadEnvFile(path.resolve('.env')); const tempDir = path.resolve('../.verification/browser-temp'); fs.mkdirSync(tempDir, { recursive: true }); process.env.TEMP = tempDir; process.env.TMP = tempDir;
const { chromium } = require('playwright'); const { PrismaClient } = require('../../backend/node_modules/@prisma/client'); const { PasswordService } = require('../../backend/dist/common/security/password.service'); const WEB = process.env.CORS_ORIGIN; const privateValues = [process.env.ADMIN_PASSWORD, process.env.JWT_SECRET];

(async () => {
 const prisma = new PrismaClient(); let browser; let project; let downloadedPath; const userIds = [];
 try {
  const roles = Object.fromEntries((await prisma.role.findMany()).map(role => [role.name, role.id])); const password = randomBytes(24).toString('hex'); privateValues.push(password); const host = await prisma.user.create({ data: { name: 'Anfitrión XMI', email: `${randomUUID()}@example.test`, passwordHash: await new PasswordService().hash(password), roleId: roles.ANFITRION } }); userIds.push(host.id); project = await prisma.project.create({ data: { name: `XMI-${randomUUID().slice(0, 8)}`, ownerId: host.id } }); const diagram = await prisma.diagram.create({ data: { projectId: project.id, name: 'Modelo XMI', classes: { create: [{ name: 'Cliente', x: 80, y: 80, attributes: { create: { name: 'id', type: 'Long', visibility: 'PRIVATE', isPrimaryKey: true } } }, { name: 'Pedido', x: 380, y: 80 }] } }, include: { classes: true } }); await prisma.umlRelation.create({ data: { diagramId: diagram.id, sourceClassId: diagram.classes.find(item => item.name === 'Cliente').id, targetClassId: diagram.classes.find(item => item.name === 'Pedido').id, type: 'ASSOCIATION', sourceMultiplicity: '1', targetMultiplicity: '0..*', label: 'realiza' } });
  browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROME_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true }); const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, acceptDownloads: true }); const errors = []; page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) }); page.on('dialog', dialog => dialog.accept());
  await page.goto(`${WEB}/login`); await page.getByLabel('Email', { exact: true }).fill(host.email); await page.getByLabel('Contraseña', { exact: true }).fill(password); await page.getByRole('button', { name: 'Iniciar sesión' }).click(); await page.waitForURL(`${WEB}/dashboard`); await page.goto(`${WEB}/projects/${project.id}/editor`); await page.getByText('Realtime: conectado').waitFor();
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Exportar XMI' }).click(); const download = await downloadPromise; downloadedPath = path.join(tempDir, `export-${randomUUID()}.xmi`); await download.saveAs(downloadedPath); const xml = fs.readFileSync(downloadedPath, 'utf8'); assert.match(xml, /xmi:XMI/); assert.match(xml, /Cliente/); assert.match(xml, /0\.\.\*/); await page.getByText('Archivo XMI exportado.').waitFor(); console.log('Exportación descarga un XMI con clases y multiplicidades.');
  const importedPath = path.join(tempDir, `import-${randomUUID()}.xmi`); fs.writeFileSync(importedPath, xml.replace('name="Cliente"', 'name="ClienteImportado"')); await page.getByLabel('Seleccionar archivo XMI').setInputFiles(importedPath); await page.getByText(/XMI importado: 2 clases y 1 relaciones/).waitFor(); await page.locator('.react-flow__node').filter({ hasText: 'ClienteImportado' }).waitFor(); assert.equal(await page.locator('.react-flow__node').getByText('Cliente', { exact: true }).count(), 0); console.log('Importación reemplaza el modelo y actualiza React Flow desde la respuesta persistida.');
  const invalidPath = path.join(tempDir, `invalid-${randomUUID()}.xmi`); fs.writeFileSync(invalidPath, '<xmi:XMI>'); await page.getByLabel('Seleccionar archivo XMI').setInputFiles(invalidPath); await page.getByRole('alert').filter({ hasText: 'XML inválido' }).waitFor(); await page.locator('.react-flow__node').filter({ hasText: 'ClienteImportado' }).waitFor(); assert.deepEqual(errors, []); console.log('XML inválido muestra error controlado y conserva el diagrama.');
  for (const file of [downloadedPath, importedPath, invalidPath]) if (file && fs.existsSync(file)) fs.unlinkSync(file);
 } finally { if (project) { await prisma.diagram.deleteMany({ where: { projectId: project.id } }); await prisma.project.deleteMany({ where: { id: project.id } }); } if (userIds.length) await prisma.user.deleteMany({ where: { id: { in: userIds } } }); await prisma.$disconnect(); if (browser) await browser.close(); }
})().catch(error => { let message = error.message; for (const value of privateValues.filter(Boolean)) message = message.split(value).join('[REDACTADO]'); console.error('Prueba XMI frontend falló:', message); process.exitCode = 1; });
